### ISSUE TITLE
How to use this solargraph?

### ISSUE THREAD

**Issue by roxma** [castwide/solargraph#10]
Hi, thanks for the project,

Where can I find the docs on how to use this project, I want to write an extension for [neovim](/neovim/neovim) with [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager)

**Comment by castwide** [comment]
Thanks for your interest.

Documentation is sparse at the moment, especially since the code went through some major restructuring for v0.13.0. I can give you some tips on where to start looking:

* Tools typically run a local server via the `solargraph server` command. Check the lib/solargraph/server.rb code to see the REST API that the server provides for clients. The endpoint that provides autocomplete suggestions is POST /suggest.
* The solargraph-utils project (https://github.com/castwide/solargraph-utils) is a Node package that demonstrates how to use the server. The VS Code extension (https://github.com/castwide/vscode-solargraph) is the most complete implementation of it.
* There's also a pre-alpha version of a vim plugin (https://github.com/hackhowtofaq/vim-solargraph).

If you have any specific questions, I'll do my best to answer them. More documentation is still on the roadmap.

**Comment by yoru** [comment]
Thank you for the project, it looks awesome. It's kinda sad it lacks documentation at the moment.

I just tried it and I got a json response with an error message: `undefined method 'gsub!' for nil:NilClass`. I'm missing something?

Ruby file (/tmp/a.rb)
```ruby
Array.n
```
Python code
```python
url = 'http://localhost:7657/suggest'
params = {
    'text': 'Array.n',
    'line': 1,
    'column': 8,
    'filename': '/tmp/a.rb',
    'workspace': '/tmp'
}
```

**Comment by castwide** [comment]
The line and column indexes are zero-based, so line should be 0 and column should be 7.

**Comment by castwide** [comment]
I've started documenting the server's web API here: https://github.com/castwide/solargraph/blob/master/SERVER.md
