### ISSUE TITLE
Document how to work with bundled gems

### ISSUE THREAD

**Issue by fsateler** [castwide/solargraph#103]
Indexing used gems with `yard gems` works, but has a problem: it only works for globally installed gems. Gems installed via bundle are invisible to yard. How can I make solargraph see my bundled gems?

**Comment by castwide** [comment]
The most comprehensive way to get documentation from bundled gems is to bundle Solargraph.

In the Gemfile:

```
gem 'solargraph', group: :development
```

Run `bundle install` and use `bundle exec yard gems` to generate the documentation. This process should work with cached or vendored gems, or even gems that are installed from a local `path`.

In order to access the gems in your project, you'll need to start the language server with bundler. In VS Code, there's a `solargraph.useBundler` option. Other clients will vary, but the command you probably want to run is `bundle exec solargraph stdio`.

**Comment by fsateler** [comment]
@castwide thanks for the detailed explanation. It would be nice if this was documented somewhere. It wasn't immediately obvious to me, as a relatively new ruby user.

**Comment by castwide** [comment]
Good point. The least I can do is add it to the README.

**Comment by castwide** [comment]
Bundler documentation is in the README for both the gem and the VS Code extension.

**Comment by fsateler** [comment]
Awesome thank you!
