### ISSUE TITLE
Diagnostics behavior.

### ISSUE THREAD

**Issue by hifall** [castwide/solargraph#113]
I have enabled diagnostics by passing `"diagnostics": true`, and solargraph seems to be reporting diagnostics issues. However, the behavior is a bit unexpected, and I wonder if it's possible to tune it.

What I am seeing is that solargraph reports a lot of warnings like:
`[Layout/EndOfLine] Carriage return character detected.`
`[Metrics/MethodLength] Method has too many lines. [13/10]`
`[Layout/IndentationWidth] Use 2 (not 4) spaces for indentation.`
`[Style/StringLiterals] Prefer single-quoted strings when you don't need string interpolation or special symbols.`
, etc.

On one hand, as shown above, these are style warnings which don't directly affect program correctness. For my situation, these warnings are not desired, and they sort of get in the way. I'd like to disable them.

On the other hand, when I try to call an undefined function, which is a real program error, solargraph doesn't report the issue. Since such an issue is critical, I'd like to have an error message shown for it.

Is it possible for such behavior in the latest version of solargraph?

**Comment by castwide** [comment]
The style warnings are coming from RuboCop, which is one of the default diagnostics reporters. You can customize its behavior with a [.rubocop.yml file](https://rubocop.readthedocs.io/en/latest/configuration/).

To disable RuboCop altogether, create a .solargraph.yml file in your project root (the `solargraph config` command generates a default one) and remove `rubocop` from the `reporters` section. See http://solargraph.org/tips for more information about configuration options.

There isn't a reporter for undefined functions yet, but I'm working on it. Mitigating false positives is a bit challenging.

**Comment by hifall** [comment]
Thanks @castwide, in addition to undefined functions, there are quite some other cases on which reporting would be helpful, including but not limited to: incorrect #args, unbalanced parenthesis, etc. Are such common scenarios on the roadmap too?

**Comment by castwide** [comment]
Incorrect args will probably fall under the same reporter as undefined functions, since they share some common functionality. A first step toward those features is the `type_not_defined` reporter. It emits warnings for method definitions that don't have corresponding `@return` and `@param` tags.

Currently diagnostics depend on the RuboCop reporter to flag syntax errors like unbalanced parentheses. It might not be immediately apparent because instead of highlighting the parenthesis, it highlights the point in code where the parser failed, which might be several lines later or even at the end of the file. I'd much prefer to highlight the parenthesis, but from what I can tell, the parser doesn't provide its location.
