### ISSUE TITLE
Using Solargraph with JRuby and Bundler

### ISSUE THREAD

**Issue by AprilArcus** [castwide/solargraph#128]
This is more of a support request than a bug, so please forgive me if this is not the appropriate place to open this conversation. My project uses jruby as its runtime, and bundler to manage gems. The documentation is clear enough that I can install the solargraph gem into my bundle in order to access completions for my gems, but if I do this then I end up adding the long startup time of jruby to the startup time of my text editor.

So, my question: is there a way to run solargraph inside YARV ruby (to benefit from the faster startup time), while retaining access to documentation from gems in a gemfile marked for use with jruby?

**Comment by castwide** [comment]
As far as I'm concerned, GitHub is an appropriate place for any bug reports, feature requests, or technical support questions for any of my public projects.  Thanks for your participation. Bringing it here can help other people with similar issues.

Solargraph shouldn't care if it uses a different Ruby runtime from the software you're developing, e.g., JRuby vs. MRI vs. Rubinius vs. whatever. The biggest issue here is making sure it has access to the same gems. (Compatibility issues are possible but should be uncommon.) One thing to remember: run `yardoc gems` in whichever Ruby environment Solargraph uses to make sure the gems are documented.

Since your Gemfile is marked for use with JRuby, you might need to jump through a couple extra hoops to get the same gems installed in YARV. If nothing else, you could manually run `gem install` for each dependency.

Anything I missed or failed to answer, or anything not working as expected, please let me know.

**Comment by drkstr101** [comment]
> Anything I missed or failed to answer, or anything not working as expected, please let me know.

It is very common for gems that depend on native extensions to break in jruby.

see: https://github.com/jruby/jruby/wiki/C-Extension-Alternatives
