### ISSUE TITLE
Does require_paths support relative paths?

### ISSUE THREAD

**Issue by nickpelone** [castwide/solargraph#143]
Related: #121 (but it may be resolved-yet-unclosed), #114 

Terribly sorry to bother, also please, please! figure out #138 because **good lord**, you've made my day to day experience with Ruby so much nicer!

Does the experimental `require_paths` config option support relative paths? Or maybe there's something else I'm missing?

I work in a big monorepo, and we have code in various places that we make available at runtime through `SITE_RUBY` and also `$LOAD_PATH` changes. (I don't expect `solargraph` to try and figure this stuff out, of course).

To give you an idea:

```
src/
  lib/
    ruby/
      our_lib/
        magic.rb
bin/
  my-program/
    .solargraph.yml
    my-program.rb
api-app/
  models/
    cool-database-table.rb
```

However, I'd like to adjust my `.solargraph.yml` file to look in these places when trying to resolve `require`s. This way, I can stop using my workaround of big globs in the `include` section, which makes `solargraph` take a long time to start and makes me need to disable `require_not_found`:

```yaml
include:
- "../../api-app/**/*.rb"
- "../../lib/ruby/**/*.rb"
```

I'd like to do instead: (from a `.solargraph.yml` in `src/bin/my-program`)

```yaml
require_paths:
- "../../lib/ruby"
- "../../api-app"
```

and then the following `require`s get resolved:

```ruby
require 'our_lib/magic' # where the file is ../../lib/ruby/our_lib/magic.rb
require 'models/cool-database-table' # where the file is ../../api-app/models/cool-database-table.rb
```

I'm not sure if it's that `require_paths` doesn't support relative paths like this, or if it's some other thing I'm not getting? I know this is a kinda unconventional setup, so apologies.

If you need any additional information, please let me know. (Or if you wanna point me at what I might want to poke at to implement the feature) Thank you so much for this gem! You've done some incredible work.

**Comment by castwide** [comment]
Thanks! I'm glad you find Solargraph useful.

The `require_paths` setting probably won't do what you want. Its only purpose is to tell Solargraph that a path it wouldn't otherwise recognize is actually valid. (It also has an outstanding issue that I hope to resolve in 0.31.1.) Right now, the only way to add `../../lib` and `../../api-app` to the map is to put them in the `include` section.

Improving the initial load time is an ongoing concern. A couple of possibilities I'm considering:

* Allow a list of directories where explicit APIs should be mapped but implementation details should be ignored. Those directories would get parsed significantly faster, with the compromise being unmapped internal variables and shallower type inference.
* Allow for the inclusion of arbitrary yardocs. This way you could generate a yardoc for e.g. `api-app` instead of remapping the source code every time Solargraph starts. It would involve the same compromise as the other solution, plus you'd need to regenerate the yardoc when the code changes.

I'm strongly leaning toward the first. If it's fast enough, it could preclude the need for the second.

Any questions or recommendations, please let me know.

**Comment by nickpelone** [comment]
Either of those would probably be fine for my uses. Perhaps I fibbed a little - maybe I _do_ want `solargraph` to be able to know about different `LOAD_PATH`s :laughing: (I have no idea what that would look like outside of just specifying directories from the user perspective, and I dunno what that would look like either in terms of implementing / burden.)

Anywho, that what I'm doing is the recommended setup for today and that you're looking to improve other underlying things for speed, etc. is good enough for me. Feel free to do whatever you see fit with the ticket.

Thank you!

**Comment by dezza** [comment]
`solargraph bundle` or if installed locally in gem `bundle exec solargraph bundle`
