### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by minkir014** [castwide/solargraph#214]
I know that it would be hard to implement to add support for debugging ruby but it's good enhancement and a very wanted thing.

**Comment by castwide** [comment]
Debugging tools are a little outside the scope of this gem. The primary features I expect to support here are static analysis (code mapping, type checking, etc.) and the language server protocol.

Your best bet is to refer to your editor's documentation for Ruby debugging support, or look for third-party extensions. In VS Code, for example, there's the [rebornix.Ruby extension](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby).

**Comment by minkir014** [comment]
You could create Debug Adapter Protocol for Ruby. I am using vs code and the extension you mentioned I know it very much but its debugger isn't very maintained and @wingrunr21 can't alone fix all the problems of it. Although a few time ago he fixed an important problem but it took him too much time because he is alone not because the extension is bad.

**Comment by castwide** [comment]
For now I'd prefer to contribute to rebornix.Ruby (which already uses the debug adapter protocol) than create a new extension. I've contributed to it in the past and will likely do so again.

If it becomes necessary to move away from rebornix.Ruby, I'd probably build a debugger as a separate extension instead of adding it to Solargraph.

**Comment by wingrunr21** [comment]
PRs welcome @minkir014

**Comment by castwide** [comment]
@minkir014 I would up writing a new gem for debuggers that use the Debug Adapter Protocol: https://github.com/castwide/readapt

There's a VS Code extension: https://marketplace.visualstudio.com/items?itemName=castwide.ruby-debug

Since it uses DAP, it ostensibly works with any compatible client, but I'd like to battle-test it in its own extension before I start recommending it for widespread use.
