### ISSUE TITLE
Markdown Libraries and Supported Rubies

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#242]
[This commit to the master branch](https://github.com/castwide/solargraph/commit/0d10b7829c9ffc8aa1dfb6731ad351e104658e7a) changes the Markdown library from Redcarpet back to Maruku.

Although [Maruku should be considered obsolete](https://benhollis.net/blog/2013/10/20/maruku-is-obsolete/), it allows for more cross-platform compatibility than either Redcarpet or kramdown; i.e., Ruby < 2.3 and JRuby are both supported. When support for Ruby < 2.3 is deprecated, switching to kramdown will become a viable option that still supports JRuby.

This is an internal detail that shouldn't have a noticeable effect for most users, but I'm reporting the change here in case anyone encounters problems with it.

**Comment by castwide** [comment]
Version 0.38.0 uses Maruku. A future version might change to kramdown, depending on the minimum Ruby version supported.

**Comment by dcermak** [comment]
Hi @castwide, I'm currently working on getting solargraph into openSUSE Tumbleweed. This has been a relatively lengthy process as it required to package quite a bunch of rubygems, but now I've hit a small roadblock with maruku. It appears to be completely unmaintained as of 2017, which bears quite the risk to include it in the openSUSE distribution (even in a rolling one like Tumbleweed). Especially given my nearly non-existent ruby knowledge, I wouldn't be able to fix security issues in it, if they should appear.

Would it be possible for solargraph to switch to kramdown or redcarpet sooner rather than later? Otherwise I'll have to defer the submission to openSUSE Tumbleweed (which is not a huge issue, as there's afaik no one actually waiting for that 😉)

**Comment by castwide** [comment]
I don't have an ETA yet. My tentative plan is to change to kramdown in v1.0, which I hope to release sometime this year. Before that, v0.39 will probably be the last version to support Ruby < 2.3.

**Comment by dcermak** [comment]
Sure, no pressure! I'll be watching this project for new releases and once Maruku is gone from the gemspec, I'll submit solargraph to openSUSE Tumbleweed.

**Comment by dcermak** [comment]
And thanks for working on Solargraph! Albeit I am not a real ruby developer, it's a life saver for me for navigating ruby projects!

**Comment by NickLion** [comment]
> as there's afaik no one actually waiting for that

There is at least me ;) Started home project for that some time ago.
