### ISSUE TITLE
Autocompletion on nested calls problem

### ISSUE THREAD

**Issue by tekert** [castwide/solargraph#440]
`5.times.map`
When typing 5.times.  'map' is not there.

**Comment by castwide** [comment]
This bug is specific to the `Integer#times` method. Its return value is not typed in the documentation, so I'll need to add it to the core fills (a set of annotations that fills gaps in the core Ruby docs). There's an additional issue with how integers are parsed that I just noticed while testing this one. I'll work on a fix for the next release.

**Comment by castwide** [comment]
Fix published in v0.41.0.

**Comment by tekert** [comment]
Thanks! enumerator completion working great now.

**Comment by tekert** [comment]
I think i found another not typed in doc
Array#find
[1].find. <- 0 results in completion.

**Comment by castwide** [comment]
Confirmed. There's a similar issue at play here, but looking into it exposed another consideration: the return value is different depending on whether the method receives a block argument. (The same is true of `times`; if it receives a block, it returns `Integer`.) I'll fix it in a patch release.

**Comment by castwide** [comment]
The core fills for `Integer#times` and `Array#find/detect` are fixed in gem 0.42.2. `Hash#find/detect` is a little more complicated, but it's on the roadmap.

**Comment by castwide** [comment]
`Hash#find/detect` work as of v0.43.0.
