### ISSUE TITLE
Formatting with nvim-lspconfig doesn't work anymore

### ISSUE THREAD

**Issue by strayer** [castwide/solargraph#455]
Since today (might have been broken earlier, not completely sure) I can't format code in nvim with nvim-lspconfig anymore. The `vim.lsp.buf.formatting()` function simply seems to do nothing. Formatting with other LSPs works. I can't find anything in the lsp.log, even with debug logging in solargraph activated.

I could find a workaround though… it seems like solargraph doesn't tell nvim (or nvim doesn't understand) that it provides formatting. When overriding the resolved capabilities, formatting works again:

```
    if server == "solargraph" then
      config.settings = {solargraph = {diagnostics = true, formatting = true, logLevel = 'debug'}}
      config.on_attach = function(client)
        on_attach(client)

        -- fix formatting
        client.resolved_capabilities.document_formatting = true
      end
    end
```

Not sure if I should file this here, at https://github.com/neovim/nvim-lspconfig or at nvim itself. Please tell me if I can provide more information in any way!

Ruby version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
Solargraph version: 0.42.3
rubocop version: 1.15.0

**Comment by CKolkey** [comment]
This has been bothering me all day. I can corroborate that solargraph isn't reporting the capability to handle document formatting.

**Comment by castwide** [comment]
I'm not 100% sure what the root cause is, but I have a suspicion. It sounds related to an initialization problem that was addressed in #436. With some clients, Solargraph would ignore the config options from the `initialize` message and only update them in response to a `workspace/didChangeConfiguration` message. That's been fixed, but it has the side effect of disabling formatting by default, which was the original intent back when formatting was more of an experimental feature.

The solution should be to send your Solargraph config in the `initialize` message's `initializationOptions` param, e.g.:

```
"initializationOptions": {
  "formatting": true
}
```

The `initializationOptions` param should probably be the same as `config.settings.solargraph`.

If this doesn't work or there still appears to be a server-side problem, please let me know.

**Comment by strayer** [comment]
This seems to be it! Passing `init_options = {formatting = true}` to the setup function of the lspconfig server makes formatting work again.

Should be something like this in a "normal" config:

```lua
require'lspconfig'.solargraph.setup({init_options = {formatting = true}})
```

**Comment by castwide** [comment]
> Should this be updated in the documentation of lspconfig then? They only mention formatting in the settings.solargraph table (see https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#solargraph)

Sounds like it. From what I can tell, `init_options` should be equivalent to `settings.solargraph`. That's essentially how it works in VS Code; the same options that are sent in the `initializationOptions` param of the `initialize` message are sent in the `settings.solargraph` param of the `workspace/didChangeConfiguration` message. There might be a better way to handle it, though.

**Comment by strayer** [comment]
I can confirm that formatting works without any workarounds after updating nvim-lspconfig. Thanks @CKolkey for fixing this!
