### ISSUE TITLE
Is it possible to speedup workspace scanning?

### ISSUE THREAD

**Issue by AlBundy33** [castwide/solargraph#467]
As mentioned in #462 I've created a simple generator the generates rb-files from our java-classes via reflection.
This seems to work but scanning the workspace takes some time.
`Scanned Z:/eclipse_projects/RubySandbox (117591 pins) in 245.5860803000396 seconds.`

In this case RubySandbox contains only my generated files (~1000) but I want to put the files in our main folder where we have much more rb-files (on folder for each customer).

I have already limited the includes via .solargraph.yml
```
include:
- "api/**/*.rb"
```

Is there something I can do to speedup `solargraph scan -v` (e.g. genreate additional files for solargraph)?

**Comment by castwide** [comment]
I don't know if there's much that can be done to improve the speed of a scan. It's an intensive process that involves performing type inference on every pin in the map, including the Ruby core and pins imported from other libraries.

The good news is that `scan` is a troubleshooting tool that you shouldn't need to run on a regular basis. I only use it when I'm trying to track down the root cause of a bug that I encountered elsewhere. For comparison, the language server typically initializes a workspace map in 10-15% of the time it takes for a full scan.

**Comment by AlBundy33** [comment]
I did this only because the initial scan in eclipse and vscode was very slow and I was not sure how long I have to wait.

Therefore I've used solargrpah scan -v to have something like a progress :-) 

After that I could use code-completion in eclipse and vscode.

My complete workspace looks like this...

```
$ find . -name *.rb | wc -l
3795
```
(including 1145 rb-files of the generated api)

**Comment by castwide** [comment]
A workspace of that size should probably get mapped in a couple of seconds. If it's still taking a long time, it might be due to a large number of gem dependencies. I don't know if there's much you can do about that.

Incidentally, if you haven't updated to Solargraph 0.43.0, it includes a few changes that might noticeably improve the performance of the language server.

**Comment by AlBundy33** [comment]
I've already updated to 0.43.0 - but I think this was yesterday after I already worked with solargraph scan.

If you say it should be faster than I'll let my colleagues test the generated api and see what they say about the performance.

At least with the manual scan it works very well in eclipse and vscode.
