### ISSUE TITLE
Ruby 3 cores

### ISSUE THREAD

**Issue by jhirn** [castwide/solargraph#488]
Hi. I just picked up a new project using ruby 3.0.2 and realized there's no cores available for ruby 3 yet. 

What is the status on that? Is there anything blocking or are they just not available yet? What issues will I face by not having the core installed?

Thanks!

**Comment by castwide** [comment]
The 3.x core documentation failed some tests due to reduced code coverage the last time I tried generating it. The 2.7.4 documentation should be mostly sufficient for the time being.

There's a good chance that the need to download cores will be eliminated in an upcoming version, with RBS handling those duties instead. Related issue: #464
