### ISSUE TITLE
Completions not working

### ISSUE THREAD

**Issue by MuhammadAdam-CodeInterview** [castwide/solargraph#565]
I have installed solargraph on Ubuntu and added below configuration in the YCMD (A code-completion & code-comprehension server) 
`gem install solargraph`
` "language_server": [{
    "name": "solargraph",
    "cmdline": [ "solargraph", "stdio" ],
    "filetypes": [ "rb" ]
  }]`
the server gets starting but while getting completions from server it does not return anything

**Comment by MuhammadAdam-CodeInterview** [comment]
Now I am able to get the completions data but this is how I am getting it.
`a = []
a.  # <-- shows nothing
a.*  # <-- shows menu
a.an # <-- shows menu`

**Comment by castwide** [comment]
I assume you're opening a file that looks like this:

```ruby
a = []
a.
```

The trailing `.` is a syntax error. The parser can't tokenize invalid code, so the file doesn't get mapped.

Solargraph works around this limitation by fixing incremental changes in the `textDocument/didChange` message that would otherwise result in a parser error. If you start with a file like this:

```ruby
a = []
a
```

...then use `textDocument/didChange` to add the `.`, Solargraph should be able to give you code completions.
