### ISSUE TITLE
Using completion in nvim requires '*' to display all matches.

### ISSUE THREAD

**Issue by pignatenko** [castwide/solargraph#75]
Using LanguageClient-neovim I am required to write something like:
```
a.*
```

Then use omnicompletion to get a full list of properties. However this is inconsistent because if I use a built in class I can write:

```
Time.
```

Then use omnicompletion to get a full list of properties. The commands being sent to the server are exactly the same though!

**Comment by castwide** [comment]
Part of the problem might be that LanguageClient-neovim does not support incremental sync for textDocument/didChange methods (https://github.com/autozimu/LanguageClient-neovim/issues/551).

When the server parses a changed file, it uses incremental edits to determine changes that should be ignored due to syntax errors. This includes many (but not all) instances of trailing periods.

I've started working on improved handling of unparseable updates from clients that send full text instead of incremental changes.

I don't normally use nvim, so there may be other issues I don't know about.

**Comment by grzesiek** [comment]
This is quite unfortunate because I believe that triggering completion after writing `something.` is the most typical use case :thinking:

**Comment by castwide** [comment]
This should be fixed with the addition of diff-lcs to handle non-incremental syncs. If problems persist, please feel free to open a new issue.
